# Interactive component

```{r}
# links referenced to assist with creating this part:
# https://stackoverflow.com/questions/58178037/updating-bar-chart-with-a-button-press
# https://stackoverflow.com/questions/21685943/change-button-text-using-d3js
```

This bar chart will display the **Percent Proficient** in state assessment in Math and RLA for all student categories represented in our data. 

To reveal the results,
You need to answer the following question by clicking on one of the options (**A, B, C, D**). You will be prompted a message based on your answer.

To see the bar chart you need to click on **solution**

***

**Which group of students do you think can benefit the most from resources in order to improve their proficiency in Math / RLA assessments?**

 * A: Children with disabilities
 * B: English learner 
 * C: Migrant
 * D: Homeless enrolled


<body>
  
  <!-- Bar Chart for SVG-->
  <svg width="500" height="500" id="svg2"></svg>
  <br> <br>
  <text x="0" y="80">Make your choices among the options by clicking the corresponding buttons and verify if you are right.</text>
  <button onclick="wrong()">A</button>
  <button onclick="right()">B</button>
  <button onclick="wrong()">C</button>
  <button onclick="wrong()">D</button>
  <p id="typo" class="fancy">Answer</p>
  <text x="0" y="80">Press the 'Solution' button to see the answer.</text>
  <button onclick="updateData()">Solution</button>
  <script src="https://d3js.org/d3.v5.min.js"></script>

  <script>
    //Bar Chart
    //Creating data
    let data2 = [{
        name: 'MAS',
        value: 10
      },
      {
        name: 'F',
        value: 10
      },
      {
        name: 'MWH',
        value: 10
      },
      {
        name: 'MIL',
        value: 10
      },
      {
        name: 'M',
        value: 10
      },
      {
        name: 'MTR',
        value: 10
      },
      {
        name: 'MBL',
        value: 10
      },
      {
        name: 'MHI',
        value: 10
      },
      {
        name: 'ECD',
        value: 10
      },
      {
        name: 'MAM',
        value: 10
      },
      {
        name: 'FCS',
        value: 10
      },
      {
        name: 'MIG',
        value: 10
      },
      {
        name: 'HOM',
        value: 10
      },
      {
        name: 'CWD',
        value: 10
      },
      {
        name: 'LEP',
        value: 10
      }
    ]
    //Creating svg, margin, width, height
    let svg2 = d3.select("#svg2")
    let margin = 30;
    let width = 500 - 2 * margin;
    let height = 500 - 2 * margin;

    //Creating chart by using g in svg2.
    let chart2 = svg2.append('g')
      .attr('transform', 'translate(30, 30)');
    //yScale
    let yScale2 = d3.scaleLinear()
      .range([height, 0])
      .domain([0, 100]);

    //append g to create y axis
    chart2.append('g')
      .call(d3.axisLeft(yScale2));

    //xScale
    let xScale2 = d3.scaleBand()
      .range([0, width])
      .domain(data2.map((d) => d.name))
      .padding(0.2);

    //append g to create x axis
    chart2.append('g')
      .attr('transform', 'translate(0, 440)')
      .call(d3.axisBottom(xScale2));

    //Selecting all in chart2 to set/append rectangular, and axis.
    chart2.selectAll()
      .data(data2)
      .enter()
      .append('rect')
      .attr('x', (d) => xScale2(d.name))
      .attr('y', (d) => yScale2(d.value))
      .attr('height', (d) => height - yScale2(d.value))
      .attr('width', xScale2.bandwidth())
      .attr("fill", "lightgreen");

    function wrong() {
      d3.select("#typo").text("It seems that this group can indeed benefit from more resources, but data shows another group with a more severe deficiency level.");
        }
    function right() {
      d3.select("#typo").text("That's correct based on our data. English learners has the highest deficiency and thus can benefit the most from more resources.");
        }
    
    function updateData() {
      let data2 = [{
        name: 'MAS',
        value: 68
      },
      {
        name: 'F',
        value: 58
      },
      {
        name: 'MWH',
        value: 57
      },
      {
        name: 'MIL',
        value: 57
      },
      {
        name: 'M',
        value: 53
      },
      {
        name: 'MTR',
        value: 53
      },
      {
        name: 'MBL',
        value: 49
      },
      {
        name: 'MHI',
        value: 48
      },
      {
        name: 'ECD',
        value: 45
      },
      {
        name: 'MAM',
        value: 44
      },
      {
        name: 'FCS',
        value: 40
      },
      {
        name: 'MIG',
        value: 38
      },
      {
        name: 'HOM',
        value: 34
      },
      {
        name: 'CWD',
        value: 29
      },
      {
        name: 'LEP',
        value: 25
      }
    ]
      let u2 = chart2.selectAll("rect")
        .data(data2)
      u2
        .enter()
        .append('rect')
        .merge(u2)
        .transition()
        .duration(2000)
        .attr('x', (d) => xScale2(d.name))
        .attr('y', (d) => yScale2(d.value))
        .attr('height', (d) => height - yScale2(d.value))
        .attr('width', xScale2.bandwidth())
        .attr("fill", "lightgreen")

    }

  </script>

***
<br>

**Mapping of Student Categories**

| Category	| Category Description |
| :-------: | :------------------- |
| MAS	      | Asian/Pacific Islander|
| F	| Female
| MWH	| White
| MIL	| Military Connected Student Status
| M	| Male
| MTR	| Two or More Races
| MBL	| Black
| MHI	| Hispanic
| ECD	| Economically disadvantaged
| MAM	| American Indian/Alaska Native
| FCS	| Foster Care Status
| MIG	| Migrant
| HOM	| Homeless Enrolled
| CWD	| Children with disabilities
| LEP	| English Learner